feat: add trigger for version validation

diff --git a/.github/workflows/check-version.yml b/.github/workflows/check-version.yml
--- a/.github/workflows/check-version.yml
+++ b/.github/workflows/check-version.yml
@@ -57,14 +57,14 @@ jobs:
         run: |
           METADATA_FILE="$CHANGED_DIR/metadata.yml"
           OPENAPI_FILE="$CHANGED_DIR/openapi-rest.yml"
-
-          # Extract API version
+          
           API_VERSION=$(yq e '.api.version' "$METADATA_FILE")
-          echo "API version from metadata.yml: $API_VERSION"
-
-          # Extract OpenAPI version
           OPENAPI_VERSION=$(yq e '.info.version' "$OPENAPI_FILE")
-          echo "OpenAPI version from openapi-rest.yml: $OPENAPI_VERSION"
-      
-      
-      
+
+      - name: Compare Versions
+        if: env.is_changed == 'true'
+        run: |
+          if [ "$API_VERSION" != "$OPENAPI_VERSION" ]; then
+            echo "Error: Versions in metadata.yml ($API_VERSION) and openapi-rest.yml ($OPENAPI_VERSION) should be the same."
+            exit 1
+          fi
