feat: add clients spec

diff --git a/.github/workflows/develop-build.yml b/.github/workflows/develop-build.yml
--- a/.github/workflows/develop-build.yml
+++ b/.github/workflows/develop-build.yml
@@ -13,7 +13,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
         with:
-          fetch-depth: 2
+          fetch-depth: 2  # Ensure previous commit is available for comparison
 
       - name: Set up JDK 17
         uses: actions/setup-java@v3
@@ -25,7 +25,7 @@ jobs:
         uses: actions/cache@v2
         with:
           path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          key: ${{ runner.os }}-maven-${{ hashFiles('/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-
 
@@ -58,20 +58,56 @@ jobs:
         id: detect_yaml
         run: |
           CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E '\.yml$' | grep -v '^\.github/')
-          
+
           if [ -z "$CHANGED_FILES" ]; then
             echo "No YAML files changed outside of .github directory."
-            exit 0
+            exit 0  # Exit gracefully if no relevant changes are detected
           fi
-          
+
           echo "changed_files=$CHANGED_FILES" >> "$GITHUB_ENV"
 
-      - name: Extract and Process Changed Files
-        id: process_files
-        if: env.changed_files != ''
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build
+    if: env.changed_files != ''
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 2
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: '17'
+
+      - name: Cache Maven packages
+        uses: actions/cache@v2
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
+
+      - name: Setup Maven settings
+        run: |
+          mkdir -p ~/.m2
+          echo "<settings>
+                  <servers>
+                    <server>
+                      <id>github</id>
+                      <username>${{ github.actor }}</username>
+                      <password>${{ secrets.APP_AFESOX }}</password>
+                    </server>
+                  </servers>
+                </settings>" > ~/.m2/settings.xml
+
+      - name: Process and Deploy Changed YAML files
         run: |
           DEPLOYMENT_DONE=false
-          
+
           for FILE in ${changed_files}; do
             if [[ $FILE == *"metadata.yml"* ]]; then
               VERSION=$(yq e '.api.version' $FILE)
@@ -82,33 +118,24 @@ jobs:
                 continue
               fi
 
-              echo "VERSION=$VERSION" >> "$GITHUB_ENV"
-              echo "NAME=$NAME" >> "$GITHUB_ENV"
-
               EXECUTIONS=$(yq e '.api.executions[].type' $FILE)
               echo "$EXECUTIONS" > executions.txt
 
               while IFS= read -r EXECUTION; do
-                echo "EXECUTION=$EXECUTION" >> "$GITHUB_ENV"
                 ARTIFACT_ID="app-afesox-${NAME}-${EXECUTION}-stable"
                 echo "Deploying ${NAME} with artifact ID ${ARTIFACT_ID}, version ${VERSION}, and execution type ${EXECUTION}..."
+          if mvn clean package -P${EXECUTION} -Dproject.version=${VERSION} && mvn deploy -P${EXECUTION} -Dproject.version=${VERSION} -Dpackage=${ARTIFACT_ID}; then
+                            echo "Deployment of ${ARTIFACT_ID} with version ${VERSION} for execution type ${EXECUTION} successful."
+                            DEPLOYMENT_DONE=true
+                          else
+                            echo "Deployment failed. Version ${VERSION} might already be deployed for ${ARTIFACT_ID}."
+                          fi
+                        done < executions.txt
+                      fi
+                    done
+                    rm -f executions.txt
 
-                if mvn clean package -P${EXECUTION} -Dproject.version=${VERSION} && mvn deploy -P${EXECUTION} -Dproject.version=${VERSION} -Dpackage=${ARTIFACT_ID}; then
-                  echo "Deployment of ${ARTIFACT_ID} with version ${VERSION} for execution type ${EXECUTION} successful."
-                  DEPLOYMENT_DONE=true
-                else
-                  echo "Deployment failed. Version ${VERSION} might already be deployed for ${ARTIFACT_ID}."
-                fi
-
-              done < executions.txt
-            fi
-          done
-          rm -f executions.txt
-
-          if [ "$DEPLOYMENT_DONE" = false ]; then
-            echo "No deployments were performed. Please check the changed files."
-            exit 1
-          fi
-
-      - name: Cleanup
-        run: rm -f changed_files.txt
+                    if [ "$DEPLOYMENT_DONE" = false ]; then
+                      echo "No deployments were performed. Please check the changed files."
+                      exit 1
+                    fi
