feat: new structure

diff --git a/.github/workflows/develop-build.yml b/.github/workflows/develop-build.yml
--- a/.github/workflows/develop-build.yml
+++ b/.github/workflows/develop-build.yml
@@ -61,6 +61,21 @@ jobs:
           VERSION=$(yq e '.info.version' apis/athssox/api-first/openapi-rest.yml)
           echo "VERSION=$VERSION" >> $GITHUB_ENV
 
+      - name: Verify version
+        id: check_version
+        run: |
+          PACKAGE_EXISTS=$(curl -s -H "Authorization: Bearer ${{ secrets.APP_AFESOX }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/vlad-vinskevitch/app-afesox/packages | \
+            jq --arg VERSION "$VERSION" '.[] | select(.version == $VERSION)')
+          
+          if [ -n "$PACKAGE_EXISTS" ]; then
+            echo "ERROR: A package with version $VERSION already exists. Exiting..."
+            exit 1
+          else
+            echo "No package with version $VERSION exists. Proceeding with deployment."
+          fi
+
       - name: Build with Maven
         run: mvn clean package
 
