feat: add clients spec

diff --git a/.github/workflows/develop-build.yml b/.github/workflows/develop-build.yml
--- a/.github/workflows/develop-build.yml
+++ b/.github/workflows/develop-build.yml
@@ -82,7 +82,8 @@ jobs:
               # Extract version and name from metadata.yml
               VERSION=$(yq e '.api.version' $FILE)
               NAME=$(yq e '.api.name' $FILE)
-          
+              EXECUTIONS=$(yq e '.executions' $FILE)
+
               # Skip if either value is not found
               if [ -z "$VERSION" ] || [ -z "$NAME" ]; then
                 echo "No version or name found in $FILE. Skipping."
@@ -97,18 +98,30 @@ jobs:
               export ARTIFACT_ID
               export NAME
 
-              echo "Deploying ${NAME} with artifact ID ${ARTIFACT_ID} and version ${VERSION}..."
+              # Loop through executions and deploy
+              for EXECUTION in $(echo "$EXECUTIONS" | yq e '.[] | .type' -); do
+                echo "Processing execution type: $EXECUTION"
 
-              # Run Maven build and deploy for the current file
-              mvn clean package -Dproject.version=${VERSION} || exit 1
+                # Find corresponding Maven profile
+                if mvn help:all-profiles | grep -q "$EXECUTION"; then
+                  echo "Found Maven profile for execution type: $EXECUTION"
           
-              if mvn deploy -Dproject.version=${VERSION} -Dpackage=${ARTIFACT_ID}; then
-                echo "Deployment of ${ARTIFACT_ID} with version ${VERSION} successful."
-                DEPLOYMENT_DONE=true
-              else
-                echo "Deployment failed. Version ${VERSION} might already be deployed for ${ARTIFACT_ID}."
-                continue
-              fi
+                  echo "Deploying ${NAME} with artifact ID ${ARTIFACT_ID} and version ${VERSION}..."
+
+                  # Run Maven build and deploy for the current file
+                  mvn clean package -P $EXECUTION -Dproject.version=${VERSION} || exit 1
+          
+                  if mvn deploy -P $EXECUTION -Dproject.version=${VERSION} -Dpackage=${ARTIFACT_ID}; then
+                    echo "Deployment of ${ARTIFACT_ID} with version ${VERSION} successful."
+                    DEPLOYMENT_DONE=true
+                  else
+                    echo "Deployment failed. Version ${VERSION} might already be deployed for ${ARTIFACT_ID}."
+                    continue
+                  fi
+                else
+                  echo "No Maven profile found for execution type: $EXECUTION"
+                fi
+              done
             fi
           done
 
