feat: new structure

diff --git a/.github/workflows/pull-request-validate.yml b/.github/workflows/pull-request-validate.yml
--- a/.github/workflows/pull-request-validate.yml
+++ b/.github/workflows/pull-request-validate.yml
@@ -23,7 +23,14 @@ jobs:
         run: |
           # Find all openapi.yml files in the repository
           OPENAPI_FILES=$(find . -type f -name 'openapi.yml')
-
+          
           if [ -z "$OPENAPI_FILES" ]; then
             echo "No OpenAPI files found to validate."
-            exit 0  # Exit with 0 to avoid
+            exit 0  # Exit with 0 to avoid failing the job if there are no openapi.yml files.
+          fi
+
+          # Iterate over each OpenAPI file and validate it
+          for FILE in $OPENAPI_FILES; do
+            echo "Validating $FILE..."
+            swagger-cli validate "$FILE" || exit 1
+          done
