feat: new structure

diff --git a/.github/workflows/pull-request-validate.yml b/.github/workflows/pull-request-validate.yml
--- a/.github/workflows/pull-request-validate.yml
+++ b/.github/workflows/pull-request-validate.yml
@@ -15,6 +15,10 @@ jobs:
         with:
           fetch-depth: 1  # Ensure we have the current commit to check files
 
+      - name: Install Spectral CLI
+        run: |
+          npm install -g @stoplight/spectral-cli
+
       - name: Install OpenAPI Generator CLI
         run: |
           npm install -g @openapitools/openapi-generator-cli
@@ -40,4 +44,7 @@ jobs:
 
             echo "Validating $FILE with openapi-generator-cli..."
             openapi-generator-cli validate -i "$FILE" || exit 1  # Validate using openapi-generator-cli
+
+            echo "Validating $FILE with spectral-cli for detailed errors..."
+            spectral lint "$FILE" || exit 1  # Validate using spectral-cli
           done
